apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hetzner-kuber
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://github.com/seekin4u/hetzner-kuber.git
  ref:
    branch: main
  secretRef:
    name: ssh-keypair
