apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretstore-sample
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: apps-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-sample
  target:
    name: secret-values
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: test

# --set replicaCount=1 \
# --set environment=stage \
# --set logLevel=debug \
# --set service.type=ClusterIP \
# --set service.port=80 \
# --set ingress.enabled=true \
# --set ingress.className=nginx \
# --set ingress.annotations."nginx\.ingress\.kubernetes\.io/rewrite-target"=/ \
# --set ingress.hosts[0].host=static.98.13.98.91.clients.your-server.de \
# --set ingress.hosts[0].paths[0].path=/stage \
# --set ingress.hosts[0].paths[0].pathType=Prefix \
# --set ingress.tls=[] \
# --set serviceAccount.create=true \
# --set serviceAccount.annotations={} \
# --set serviceAccount.name="" \
# --set nameOverride="" \
# --set fullnameOverride=my-project-stage-hello-world
