apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretstore-sample
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: apps-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-sample
  target:
    name: secret-values
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example2
  namespace: apps-stage
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-sample
  target:
    name: test2
    creationPolicy: Owner
data:
  - secretKey: replicaCount
    remoteRef:
      key: test2
      property: replicaCount

  - secretKey: environment
    remoteRef:
      key: test2
      property: environment

  - secretKey: logLevel
    remoteRef:
      key: test2
      property: logLevel

  - secretKey: service_type
    remoteRef:
      key: test2
      property: service.type

  - secretKey: service_port
    remoteRef:
      key: test2
      property: service.port

  - secretKey: ingress_enabled
    remoteRef:
      key: test2
      property: ingress.enabled

  - secretKey: ingress_className
    remoteRef:
      key: test2
      property: ingress.className

  - secretKey: ingress_rewrite_target
    remoteRef:
      key: test2
      property: ingress.annotations."nginx.ingress.kubernetes.io/rewrite-target"

  - secretKey: ingress_host_0_host
    remoteRef:
      key: test2
      property: ingress.hosts.0.host

  - secretKey: ingress_host_0_path_0_path
    remoteRef:
      key: test2
      property: ingress.hosts.0.paths.0.path

  - secretKey: ingress_host_0_path_0_pathType
    remoteRef:
      key: test2
      property: ingress.hosts.0.paths.0.pathType

  - secretKey: serviceAccount_create
    remoteRef:
      key: test2
      property: serviceAccount.create

  - secretKey: serviceAccount_name
    remoteRef:
      key: test2
      property: serviceAccount.name

  - secretKey: nameOverride
    remoteRef:
      key: test2
      property: nameOverride

  - secretKey: fullnameOverride
    remoteRef:
      key: test2
      property: fullnameOverride
