apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretstore-sample
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: apps-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-sample
  target:
    name: secret-values
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example2
  namespace: apps-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-sample
  target:
    name: secret-values2
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: test2

  data:
    # top-level
    - secretKey: replicaCount
      remoteRef:
        key: my-config-secret
        property: replicaCount

    - secretKey: environment
      remoteRef:
        key: my-config-secret
        property: environment

    - secretKey: logLevel
      remoteRef:
        key: my-config-secret
        property: logLevel

    - secretKey: nameOverride
      remoteRef:
        key: my-config-secret
        property: nameOverride

    - secretKey: fullnameOverride
      remoteRef:
        key: my-config-secret
        property: fullnameOverride

    # service.*
    - secretKey: service_type
      remoteRef:
        key: my-config-secret
        property: service.type

    - secretKey: service_port
      remoteRef:
        key: my-config-secret
        property: service.port

    # ingress.*
    - secretKey: ingress_enabled
      remoteRef:
        key: my-config-secret
        property: ingress.enabled

    - secretKey: ingress_className
      remoteRef:
        key: my-config-secret
        property: ingress.className

    # ingress.annotations.*
    - secretKey: ingress_annotations_rewrite_target
      remoteRef:
        key: my-config-secret
        property: ingress.annotations."nginx.ingress.kubernetes.io/rewrite-target"

    # ingress.hosts[0]
    - secretKey: ingress_host_0_host
      remoteRef:
        key: my-config-secret
        property: ingress.hosts.0.host

    # ingress.hosts[0].paths[0]
    - secretKey: ingress_host_0_paths_0_path
      remoteRef:
        key: my-config-secret
        property: ingress.hosts.0.paths.0.path

    - secretKey: ingress_host_0_paths_0_pathType
      remoteRef:
        key: my-config-secret
        property: ingress.hosts.0.paths.0.pathType

    # serviceAccount.*
    - secretKey: serviceAccount_create
      remoteRef:
        key: my-config-secret
        property: serviceAccount.create

    - secretKey: serviceAccount_name
      remoteRef:
        key: my-config-secret
        property: serviceAccount.name

