apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretstore-sample
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: apps-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-sample
  target:
    name: secret-values
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example2
  namespace: apps-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-sample
  target:
    name: secret-values2
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: test2

  data:
    - secretKey: replicaCount
      remoteRef:
        key: test2
        property: envs.replicaCount

    - secretKey: environment
      remoteRef:
        key: test2
        property: envs.environment

    - secretKey: logLevel
      remoteRef:
        key: test2
        property: envs.logLevel

    - secretKey: nameOverride
      remoteRef:
        key: test2
        property: envs.nameOverride

    - secretKey: fullnameOverride
      remoteRef:
        key: test2
        property: envs.fullnameOverride

    - secretKey: service_type
      remoteRef:
        key: test2
        property: envs.service.type

    - secretKey: service_port
      remoteRef:
        key: test2
        property: envs.service.port

    - secretKey: ingress_enabled
      remoteRef:
        key: test2
        property: envs.ingress.enabled

    - secretKey: ingress_className
      remoteRef:
        key: test2
        property: envs.ingress.className

    - secretKey: ingress_annotations_rewrite_target
      remoteRef:
        key: test2
        property: "envs.ingress.annotations.nginx.ingress.kubernetes.io/rewrite-target"

    - secretKey: ingress_host_0_host
      remoteRef:
        key: test2
        property: envs.ingress.hosts.0.host

    - secretKey: ingress_host_0_paths_0_path
      remoteRef:
        key: test2
        property: envs.ingress.hosts.0.paths.0.path

    - secretKey: ingress_host_0_paths_0_pathType
      remoteRef:
        key: test2
        property: envs.ingress.hosts.0.paths.0.pathType

    - secretKey: serviceAccount_create
      remoteRef:
        key: test2
        property: envs.serviceAccount.create

    - secretKey: serviceAccount_name
      remoteRef:
        key: test2
        property: envs.serviceAccount.name

