apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-project-stage
  namespace: apps-stage
spec:
  interval: 1m

  chart:
    spec:
      chart: hello-world
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: hetzner-kuber
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: my-project-stage-values
      valuesKey: values.yaml
