apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-project-stage
  namespace: apps-stage
spec:
  interval: 1m

  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: hello-world
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: hetzner-kuber
        namespace: flux-system

  valuesFrom:
    
    - kind: Secret
      name: my-project-stage-secret
      valuesKey: FRUIT
      targetPath: fruit

    - kind: Secret
      name: secret-values2
      valuesKey: replicaCount
      targetPath: replicaCount

    - kind: Secret
      name: secret-values2
      valuesKey: environment
      targetPath: environment

    - kind: Secret
      name: secret-values2
      valuesKey: logLevel
      targetPath: logLevel

    - kind: Secret
      name: secret-values2
      valuesKey: nameOverride
      targetPath: nameOverride

    - kind: Secret
      name: secret-values2
      valuesKey: fullnameOverride
      targetPath: fullnameOverride

    # service.*
    - kind: Secret
      name: secret-values2
      valuesKey: service_type
      targetPath: service.type

    - kind: Secret
      name: secret-values2
      valuesKey: service_port
      targetPath: service.port

    # ingress.*
    - kind: Secret
      name: secret-values2
      valuesKey: ingress_enabled
      targetPath: ingress.enabled

    - kind: Secret
      name: secret-values2
      valuesKey: ingress_className
      targetPath: ingress.className

    # ingress.annotations.*
    - kind: Secret
      name: secret-values2
      valuesKey: ingress_annotations_rewrite_target
      targetPath: ingress.annotations.rewriteTarget

    # ingress.hosts[0]
    - kind: Secret
      name: secret-values2
      valuesKey: ingress_host_0_host
      targetPath: ingress.hosts[0].host

    # ingress.hosts[0].paths[0]
    - kind: Secret
      name: secret-values2
      valuesKey: ingress_host_0_paths_0_path
      targetPath: ingress.hosts[0].paths[0].path

    - kind: Secret
      name: secret-values2
      valuesKey: ingress_host_0_paths_0_pathType
      targetPath: ingress.hosts[0].paths[0].pathType

    # serviceAccount.*
    - kind: Secret
      name: secret-values2
      valuesKey: serviceAccount_create
      targetPath: serviceAccount.create

    - kind: Secret
      name: secret-values2
      valuesKey: serviceAccount_name
      targetPath: serviceAccount.name

#key FRUIT from the secret will become key fruit in the helm values with a value from FRUIT
#important due to https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set
