apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-project-stage
  namespace: apps-stage
spec:
  interval: 1m

  driftDetection:
    mode: enabled
    # ignore:
    #   - paths: ["/spec/replicas"]


  chart:
    spec:
      chart: hello-world
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: hetzner-kuber
        namespace: flux-system

  valuesFrom:
    # - kind: ConfigMap
    #   name: my-project-stage-values
    #   valuesKey: values.yaml

    # - kind: ConfigMap
    #   name: my-project-stage-values
    #   valuesKey: FRUIT
    #   targetPath: fruit

    # - kind: ConfigMap
    #   name: my-project-stage-values
    #   valuesKey: TEST
    #   targetPath: test
    - kind: Secret
      name: my-project-stage-secret
      valuesKey: values.yaml
    
    - kind: Secret
      name: my-project-stage-secret
      valuesKey: FRUIT
      targetPath: fruit
      
    - kind: Secret
      name: secret-values
      valuesKey: test
      targetPath: test

#key FRUIT from the secret will become key fruit in the helm values with a value from FRUIT
#important due to https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set
