apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-project-stage
  namespace: apps-stage
spec:
  interval: 1m

  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: flux2-sync
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: my-project-stage-values
      valuesKey: values.yaml
