apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-project-dev
  namespace: apps-dev
spec:
  interval: 1m

  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: flux2-sync
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: my-project-dev-values
