apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-project-dev
  namespace: apps-dev
spec:
  interval: 1m

  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: hetzner-kuber
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: my-project-dev-values
      valuesKey: values.yaml
